#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# default applications
export TERM="xterm-256color"

# support qt5 styling with qt5ct
export QT_QPA_PLATFORMTHEME="qt5ct"

# fix GTK Dbus error messages
export NO_AT_BRIDGE=1

# colored, highlighted less (old)
# export LESS='-R'
# export LESSOPEN='|~/.lessfilter %s'

# setup virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export WORKON_CACHE=$WORKON_HOME/.pip-cache
export VIRTUALENV_PYTHON=/usr/bin/python3

# set up Wine
export WINEARCH="win32"
export WINEPREFIX=~/.winetricks/

